Exploration of labeled versus inferred versus non-inferred trips
Don't think we can use inferred labels given that they are also the output of
an algorithm with its own error.

+ also ignore "Prefer Not To Say".

```
data = data[~data['available_modes'].isin(['None', 'Prefer not to say'])]
```

Without the change, I get the error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-28-ba060be6a019> in <module>
    129
    130 # Add availability variables to data
--> 131 data = add_mode_availability(data, availability_codes, 'available_modes', 'Mode_confirm', 'Replaced_mode')

<ipython-input-28-ba060be6a019> in add_mode_availability(data, availability_codes, availability_col, choice_col, replaced_col)
    115                 i+=1
    116                 continue
--> 117             options = [availability_codes[x] for x in available.split(';')]
    118             # Chosen mode must be in the available modes list, if mode was chosen it is assumed available
    119             # SWAP THIS LINE TO INCLUDE REPLACED MODE IN THE CHOICE SET (FOR VISUALS AT END)

<ipython-input-28-ba060be6a019> in <listcomp>(.0)
    115                 i+=1
    116                 continue
--> 117             options = [availability_codes[x] for x in available.split(';')]
    118             # Chosen mode must be in the available modes list, if mode was chosen it is assumed available
    119             # SWAP THIS LINE TO INCLUDE REPLACED MODE IN THE CHOICE SET (FOR VISUALS AT END)

KeyError: 'Prefer not to say'
```