Create multiple versions of the labeled confirmed trip based on user input
The three options are:
- ONLY_LABELED: for only the labeled subset. for the sensitivity analysis, this would be a user who labeled all their trips
- ONLY_SENSED: using only the sensed modes (walk,bike,car,bus,train). for the sensitivity analysis, this would to simulate a user with no labels
- BEST_AVAILABLE: user label, falling back to best label assist, falling back to best sensed label.for the sensitivity analysis, this would to simulate a user with partial labels

+ change the mapping of the primary sensed mode to correspond with label assist
so that the downstream code (e.g. mode_map from mode_confirm to Mode_confirm)
works properly

Note that if many parts of the code will NOT work for sensed labels since some kinds of labels are missing (e.g. ridehail)

+ minor code fixes around refactoring the display of numbers
+ @zackaemmer, you might want to add more of these as you work through the analyses as yet another sanity check

Testing done:
- Ran with all three options
- `ONLY_LABELED` and `BEST_AVAILABLE` run through
- `ONLY_SENSED` takes a long time, so I ran it on the first 100 trips

```
elif input_dataset == "ONLY_SENSED":
    expanded_ct = expanded_ct.head(100)
    expanded_ct.mode_confirm = expanded_ct.apply(lambda row: get_primary_sensed_mode(row), axis=1)
```

and it fails with

```
KeyError: "['tt_ridehail', 'tt_transit', 'tt_walk', 'tt_s_micro'] not in index"
```

while training the random forest model

```
X = df_train[feature_list].values
```

Note also that I had a preliminary fix for this; sharing it here in case it helps

```
if input_dataset == "ONLY_SENSED":
    # Remove features that don't exist
    remove_list = []
    for fn in feature_list:
        if fn not in df_train.columns:
            print("NO DATA FOR FEATURE %s" % fn)
            remove_list.append(fn)
    for rn in remove_list:
        feature_list.remove(rn)
```